name: 'Gigalixir Review Action'
description: 'Deploy to Gigalixir'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  GIGALIXIR_USERNAME:
    description: 'Your Gigalixir username'
    required: true
  GIGALIXIR_PASSWORD:
    description: 'Your Gigalixir password'
    required: true
  SSH_PRIVATE_KEY:
    description: 'Your ssh private key that is paired with a public key that is uploaded to Gigalixir'
    required: true
  GIGALIXIR_APP:
    description: 'Your gigalixir app name.  Will be created if not existing'
    required: true
  MIGRATIONS:
    description: 'Configuration for migrations'
    required: true
    default: true

runs:
  using: 'node12'
  main: 'dist/index.js'
