name: "Gigalixir Review Action"
description: "Deploy to Gigalixir"
branding:
  icon: "arrow-up-circle"
  color: "green"
inputs:
  GIGALIXIR_USERNAME:
    description: "Your Gigalixir username"
    required: true
  GIGALIXIR_PASSWORD:
    description: "Your Gigalixir password"
    required: true
  SSH_PRIVATE_KEY:
    description: "Your ssh private key that is paired with a public key that is uploaded to Gigalixir"
    required: true
  GIGALIXIR_APP:
    description: "Your gigalixir app name.  Will be created if not existing"
    required: true
  MIGRATIONS:
    description: "Configuration for migrations"
    required: true
    default: true
  CREATE_DATABASE:
    description: "Automatically create a free database for a new app"
    required: true
    default: false
  DATABASE_URL:
    description: "Pass in the URL to an existing Database to use"
    required: false
    default: ""
  SET_URL_HOST:
    description: "Set up the URL_HOST env var for a new app"
    required: false
    default: true
  CONFIG:
    description: "Configuration for env vars"
    required: false
    default: ""

runs:
  using: "node12"
  main: "dist/index.js"
